---
resources:
  - name: version
    type: semver
    source:
      driver: git
      initial_version: 0.0.1
      uri: https://github.com/moriyamaES/semver-test.git
      branch: main
      file: number
      private_key: ((private-key))

jobs:
  - name: bump-version
    public: true
    serial: true
    plan:
      # - get: trigger-resource
      #   trigger: true
      - get: version
        params: {bump: patch}
      # - task: a-thing-that-needs-a-version
      - put: version
        params: {file: version/number}
      - task: display-version
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          inputs:
            - name: version
          run:
            path: cat
            args: [version/number]
